---
title: "Oxide’s compensation model: How is it going?"
date: "2025-05-01"
---

= Oxide’s compensation model: How is it going?

== How it started

Four years ago, we were struggling to hire. Our team was small (~23
employees), and we knew that we needed many more people to execute on our
https://www.youtube.com/watch?v=ikn7ovpjdIg[audacious vision].  While we had
had success hiring in our personal networks, those networks now felt tapped;
we needed to get further afield.  As is our wont, we got together as a team
and brainstormed: how could we get a bigger and broader applicant pool?  One
of our engineers, Sean, shared some personal experience: that
https://oxide.computer/principles[Oxide's principles and values] were very
personally important to him -- but that when he explained them to people
unfamiliar with the company, they were (understandably?) dismissed as
corporate claptrap.  Sean had found, however, that there was one surefire way
to cut through the skepticism:  to explain our approach to compensation.
Maybe, Sean wondered, we should talk about it publicly?

"I could certainly write a blog entry explaining it," I offered.  At this
suggestion, the team practically lunged with enthusiasm: the reaction was so
uniformly positive that I have to assume that everyone was sick of explaining
this most idiosyncratic aspect of Oxide to friends and family.  So what was
the big deal about our compensation?  Well, as a I wrote in the resulting
piece,
https://oxide.computer/blog/compensation-as-a-reflection-of-values[Compensation
as a Reflection of Values], our compensation is not merely transparent, but
uniform.  The piece -- unsurprisingly, given the evergreen hot topic that is
compensation -- got a ton of attention.  While some of that attention was
negative (despite the piece trying to frontrun every HN hater!), much of it was
positive -- and everyone seemed to be at least intrigued.

And in terms of its initial purpose, the piece succeeded beyond our wildest
imagination: it brought a surge of new folks interested in the company.  Best
of all, the people new to Oxide were interested for all of the right reasons:
not the compensation _per se_, but for the values that the compensation
represents.  The deeper they dug, the more they found to like -- and many who
learned about Oxide for the first time through that blog entry we now count as
long-time, cherished colleagues.

That blog entry was a long time ago now, and today we have ~75 employees
(and a https://oxide.computer/blog/the-cloud-computer[shipping product]!);
how is our compensation model working out for us?

== How it's going

Before we get into our deeper findings, two updates that are so important that
we have updated the blog entry itself.  First, the dollar figure itself
continues to increase over time (as of this writing in 2025, $207,264);
things definitely haven't gotten (and aren't
getting!) any cheaper.  And second, we _did_ introduce variable compensation for
some sales roles.  Yes, those roles can make more than the rest of us -- but
they can also make less, too.  And, importantly:  if/when those folks are
making more than the rest of us, it's because they're selling a lot -- a
result that can be celebrated by everyone!

Those critical updates out of the way, how is it working?  There have been a
lot of surprises along the way, mostly (all?) of the positive variety.  A
couple of things that we have learned:

*People take their own performance really seriously.*  When some outsiders
hear about our compensation model, they insist that it can't possibly work
because "everyone will slack off." I have come to find this concern to be more
revealing of the person making the objection than of our model, as our
experience has been in fact the opposite: in my one-on-one conversations with
team members, a frequent subject of conversation is people who are concerned
that they aren't doing enough (or that they aren't doing the right thing, or
that their work is progressing slower than they would like).  I find my job is
often to help quiet this inner critic while at the same time stoking what I
feel is a healthy urge:  when one holds one's colleagues in high regard, there
is an especially strong desire to help contribute -- to prove oneself worthy
of a superlative team.  Our model allows people to focus on their own
contribution (whatever it might be).

*People take hiring _really_ seriously.*  When evaluating a peer (rather
than a subordinate), one naturally has high expectations -- and because (in
the sense of our wages, anyway) everyone at Oxide is a peer, it shouldn't be
surprising that folks have very high expectations for potential future
colleagues.  And because the
https://rfd.shared.oxide.computer/rfd/3[Oxide hiring process] is writing
intensive, it allows for candidates to be thoroughly reviewed by Oxide
employees -- who are tough graders!  It is, bluntly, really hard to get
a job at Oxide.

*It allows us to internalize the importance of different roles.*  One of the
more incredible (and disturbingly frequent) objections I have heard is: "But
is that what you’ll pay support folks?" I continue to find this question
offensive, but I no longer find it surprising: the specific dismissal of
support roles reveals a widespread and corrosive devaluation of those closest
to customers. My rejoinder is simple: think of the best support engineers
you've worked with; what were they worth? Anyone who has shipped complex
systems knows these extraordinary people -- calm under fire, deeply technical,
brilliantly resourceful, profoundly empathetic -- are invaluable to the
business. So what if you built a team entirely of folks like that? The
response has usually been: well, sure, if you're going to only hire _those_
folks. Yeah, we are -- and we have!

*It allows for fearless versatility.* A bit of a corollary to the
above, but subtly different: even though we (certainly!) hire and select for
certain roles, our uniform compensation means we can in fact think primarily
in terms of _people_ unconfined by those roles.  That is, we can be very fluid
about what we're working on, without fear of how it will affect a perceived
career trajectory.  As a concrete example: we had a large customer that wanted
to put in place a program for some of the additional work they wanted to see
in the product.  The complexity of their needs required dedicated program
management resources that we couldn't spare, and in another more static
company we would have perhaps looked to hire.  But in our case, two folks came
together -- CJ from operations, and Izzy from support -- and did something
together that was in some regards new to both of them (and was neither of
their putative full-time jobs!)  The result was indisputably successful:  the
customer loved the results, and two terrific people got a chance to work
closely together without worrying about who was dotted-lined to whom.

*It has allowed us to organizationally scale.* Many organizations describe
themselves as flat, and a reasonable rebuttal to this are the "shadow
hierarchies" created by the
https://en.wikipedia.org/wiki/The_Tyranny_of_Structurelessness[tyranny of
structurelessness].  And indeed, if one were to read (say)
https://cdn.fastly.steamstatic.com/apps/valve/Valve_NewEmployeeHandbook.pdf[Valve's
(in)famous handbook], the autonomy seems great -- but the stack ranking
decidedly less so, especially because the handbook is conspicuously silent on
the subject of compensation.  (Unsurprisingly,
https://www.pcgamer.com/ex-valve-employee-describes-ruthless-industry-politics/[compensation
was weaponized at Valve], which descended into
https://www.wired.com/2013/07/wireduk-valve-jeri-ellsworth/[toxic
cliquishness].) While we believe that autonomy _is_ important to do one's best
work, we also have a clear structure at Oxide in that Steve Tuck (Oxide
co-founder and CEO) is
in charge.  He has to be:  he is held accountable to our investors -- and he
must have the latitude to make decisions.  Under Steve, it is true that
we _don't_ have layers of middle management.  Might we need some in the
future?  Perhaps, but what fraction of middle management in a company is
dedicated to -- at some level -- determining who gets what in terms of
compensation?  What happens when you eliminate that burden completely?

*It frees us to both lead and follow.* We expect that
every Oxide employee has the capacity to lead others -- and we tap this
capacity frequently.  Of course, a company in which everyone is trying to
direct all traffic all the time would be a madhouse, so we also very much rely
on following one another too!  Just as our compensation model allows us to
internalize the values of different roles, it allows us to appreciate the
value of *both* leading and following, and empowers us each with the judgement
to know when to do which.  This isn't always easy or free of ambiguity, but
this particular dimension of our versatility has been essential -- and
our compensation model serves to encourage it.

*It causes us to hire carefully and deliberately.* Of course, one should
_always_ hire carefully and deliberately, but this often isn't the case -- and
many a startup has been ruined by reckless expansion of headcount.  One of the
roots of this can be found in a dirty open secret of Silicon Valley middle
management: its ranks are taught to grade their career by the number of
reports in their organization.  Just as if you were to compensate software
engineers based on the number of lines of code they wrote, this results in
perverse incentives and predictable disasters -- and any Silicon Valley vet
will have plenty of horror stories of middle management jockeying for reqs or
reorgs when they should have been focusing on product and customers.  When
you can eliminate middle management, you eliminate this incentive.  We grow
the team not because of someone's animal urges to have the largest possible
organization, but rather because we are at a point where adding people will
allow us to better serve our market and customers.

*It liberates feedback from compensation.* Feedback is, of course, very
important:  we all want to know when and where we're doing the right thing!
And of course, we want to know too where there is opportunity for improvement.
However, Silicon Valley has historically tied feedback so tightly to
compensation that it has ceased to even pretend to be constructive:  if it
needs to be said, performance review processes aren't, in fact, about
improving the performance of the team, but rather quantifying and
stack-ranking that performance for purposes of compensation.  When
compensation is moved aside, there is a kind of liberation for feedback
itself:  because feedback is now entirely earnest, it can be expressed and
received thoughtfully.

*It allows people to focus on doing the right thing.*  In a world of
traditional, compensation-tied performance review, the organizational priority
is around those things that affect compensation -- even at the expense of
activity that clearly benefits the company.  This leads to all sorts of wild
phenomena, and most technology workers will be able to tell stories of doing
things that were clearly right for the company, but having to hide it from
management that thought only narrowly in terms of their own stated KPIs and
MBOs.  By contrast, over and over (and over!) again, we have found that people
do the right thing at Oxide -- even if (especially if?) no one is looking.
The beneficiary of that right thing?  More often than not, it's our customers,
who have uniformly praised the team for going above and beyond.

*It allows us to focus on the work that matters.*  Relatedly, when
compensation is non-uniform, the process to figure out (and maintain) that
non-uniformity is laborious.  All of that work -- of line workers assembling
packets explaining themselves, of managers arming themselves with those
packets to fight in the arena of organizational combat, and then of those same
packets ultimately being regurgitated back onto something called a review --
is _work_. Assuming such a process is executed perfectly (something which I
suppose is possible in the abstract, even though I personally have never seen
it), this is work that does not in fact advance the mission of the company.
Not having variable compensation gives us all of that time and energy back to
do the _actual_ work -- the stuff that matters.

*It has stoked an extraordinary sense of teamwork.* For me personally -- and
as https://www.youtube.com/watch?v=cAFD2bq1_tU&t=2854s[I relayed on an episode
of _Software Misadventures_] -- the highlights of my career have been being a
part of an extraordinary team.  The currency of a team is mutual trust, and
while uniform compensation certainly isn't the only way to achieve that trust,
boy does it ever help!  As Steve and I have told one another more times that
we can count:  we are so lucky to work on this team, with its extraordinary
depth and breadth.

While our findings have been very positive, I would still reiterate what we
said four years ago:  we don't know what the future holds, and it's easier to
make an unwavering commitment to the transparency rather than the uniformity.
That said, the uniformity has had so many positive ramifications that the model
feels more important than ever.  We are beyond the point of this being a
curiosity; it's been essential for building a mission-focused team taking on
a problem larger than ourselves.  So it's not a fit for everyone -- but if
you are seeking an extraordinary team solving hard problems in service to
customers, https://oxide.computer/careers[consider Oxide]!


